//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfilLongitudinal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strEjeLong {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strEjeLong() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PerfilLongitudinal.strEjeLong", typeof(strEjeLong).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A clotoide .
        /// </summary>
        public static string aclotoide {
            get {
                return ResourceManager.GetString("aclotoide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azimut final .
        /// </summary>
        public static string azimutfinal {
            get {
                return ResourceManager.GetString("azimutfinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro curva X .
        /// </summary>
        public static string centrocurvax {
            get {
                return ResourceManager.GetString("centrocurvax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro curva Y .
        /// </summary>
        public static string centrocurvay {
            get {
                return ResourceManager.GetString("centrocurvay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curva.
        /// </summary>
        public static string curva {
            get {
                return ResourceManager.GetString("curva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diferencia de pendientes.
        /// </summary>
        public static string difpen {
            get {
                return ResourceManager.GetString("difpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento .
        /// </summary>
        public static string elemento {
            get {
                return ResourceManager.GetString("elemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cota de entrada.
        /// </summary>
        public static string entradaCota {
            get {
                return ResourceManager.GetString("entradaCota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PK de entrada.
        /// </summary>
        public static string entradaPK {
            get {
                return ResourceManager.GetString("entradaPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clotoide.
        /// </summary>
        public static string espiral {
            get {
                return ResourceManager.GetString("espiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Línea.
        /// </summary>
        public static string linea {
            get {
                return ResourceManager.GetString("linea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitud del acuerdo.
        /// </summary>
        public static string longitud {
            get {
                return ResourceManager.GetString("longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitud de trazado .
        /// </summary>
        public static string longitudTrazado {
            get {
                return ResourceManager.GetString("longitudTrazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen derecha .
        /// </summary>
        public static string margender {
            get {
                return ResourceManager.GetString("margender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen izquierda .
        /// </summary>
        public static string margenizq {
            get {
                return ResourceManager.GetString("margenizq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro Kv.
        /// </summary>
        public static string parametro {
            get {
                return ResourceManager.GetString("parametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente de entrada.
        /// </summary>
        public static string pendiente {
            get {
                return ResourceManager.GetString("pendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peralte (%) .
        /// </summary>
        public static string peralte {
            get {
                return ResourceManager.GetString("peralte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.K. final .
        /// </summary>
        public static string pkfin {
            get {
                return ResourceManager.GetString("pkfin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.K. inicial .
        /// </summary>
        public static string pkini {
            get {
                return ResourceManager.GetString("pkini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto fin X .
        /// </summary>
        public static string puntofinx {
            get {
                return ResourceManager.GetString("puntofinx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto fin Y .
        /// </summary>
        public static string puntofiny {
            get {
                return ResourceManager.GetString("puntofiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto inicio X .
        /// </summary>
        public static string puntoinix {
            get {
                return ResourceManager.GetString("puntoinix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto inicio Y .
        /// </summary>
        public static string puntoiniy {
            get {
                return ResourceManager.GetString("puntoiniy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio .
        /// </summary>
        public static string radio {
            get {
                return ResourceManager.GetString("radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cota salida.
        /// </summary>
        public static string salidaCota {
            get {
                return ResourceManager.GetString("salidaCota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PK de salida.
        /// </summary>
        public static string salidaPK {
            get {
                return ResourceManager.GetString("salidaPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmento.
        /// </summary>
        public static string segmento {
            get {
                return ResourceManager.GetString("segmento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentido giro .
        /// </summary>
        public static string sentgiro {
            get {
                return ResourceManager.GetString("sentgiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solución.
        /// </summary>
        public static string solucion {
            get {
                return ResourceManager.GetString("solucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo .
        /// </summary>
        public static string tipo {
            get {
                return ResourceManager.GetString("tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variación MI .
        /// </summary>
        public static string varimi {
            get {
                return ResourceManager.GetString("varimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variación MD .
        /// </summary>
        public static string varmd {
            get {
                return ResourceManager.GetString("varmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vértice .
        /// </summary>
        public static string vertice {
            get {
                return ResourceManager.GetString("vertice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cota del vértice.
        /// </summary>
        public static string verticeCota {
            get {
                return ResourceManager.GetString("verticeCota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PK del vértice.
        /// </summary>
        public static string verticePK {
            get {
                return ResourceManager.GetString("verticePK", resourceCulture);
            }
        }
    }
}
