//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tadLayLan.Tdi {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strFrmPtoIniFin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strFrmPtoIniFin() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tadLayLan.Tdi.strFrmPtoIniFin", typeof(strFrmPtoIniFin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definir azimut.
        /// </summary>
        public static string uiAzimutChecked {
            get {
                return ResourceManager.GetString("uiAzimutChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azimut llegada [º].
        /// </summary>
        public static string uiAzimutLlegadaValor {
            get {
                return ResourceManager.GetString("uiAzimutLlegadaValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azimut salida [º].
        /// </summary>
        public static string uiAzimutSalidaValor {
            get {
                return ResourceManager.GetString("uiAzimutSalidaValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definir punto en superficie....
        /// </summary>
        public static string uiBtnSelectPunto {
            get {
                return ResourceManager.GetString("uiBtnSelectPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definir punto por coordenadas....
        /// </summary>
        public static string uiBtnWritePunto {
            get {
                return ResourceManager.GetString("uiBtnWritePunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definir longitud.
        /// </summary>
        public static string uiLongitudChecked {
            get {
                return ResourceManager.GetString("uiLongitudChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud llegada [m].
        /// </summary>
        public static string uiLongitudLlegadaValor {
            get {
                return ResourceManager.GetString("uiLongitudLlegadaValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Considerar longitud recta .
        /// </summary>
        public static string uiLongitudRectaConsiderar {
            get {
                return ResourceManager.GetString("uiLongitudRectaConsiderar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud salida [m].
        /// </summary>
        public static string uiLongitudSalidaValor {
            get {
                return ResourceManager.GetString("uiLongitudSalidaValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definir pendiente.
        /// </summary>
        public static string uiPendienteChecked {
            get {
                return ResourceManager.GetString("uiPendienteChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente llegada [%].
        /// </summary>
        public static string uiPendienteLLegadaValor {
            get {
                return ResourceManager.GetString("uiPendienteLLegadaValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente salida [%].
        /// </summary>
        public static string uiPendienteSalidaValor {
            get {
                return ResourceManager.GetString("uiPendienteSalidaValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto destino.
        /// </summary>
        public static string uiPuntoDestino {
            get {
                return ResourceManager.GetString("uiPuntoDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto origen.
        /// </summary>
        public static string uiPuntoOrigen {
            get {
                return ResourceManager.GetString("uiPuntoOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a X.
        /// </summary>
        public static string uiX {
            get {
                return ResourceManager.GetString("uiX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Y.
        /// </summary>
        public static string uiY {
            get {
                return ResourceManager.GetString("uiY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Z.
        /// </summary>
        public static string uiZ {
            get {
                return ResourceManager.GetString("uiZ", resourceCulture);
            }
        }
    }
}
