//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tadLayLan.Tdi {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strFrmSolucion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strFrmSolucion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tadLayLan.Tdi.strFrmSolucion", typeof(strFrmSolucion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente distancia eje de visib..
        /// </summary>
        public static string ucCoefDistanciaEje {
            get {
                return ResourceManager.GetString("ucCoefDistanciaEje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente longitud tramo.
        /// </summary>
        public static string ucCoefDistanciaTramo {
            get {
                return ResourceManager.GetString("ucCoefDistanciaTramo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Radios de curvas condicionados a longitudes de rectas según criterio de Llim.
        /// </summary>
        public static string ucRadioCondicionadoLmin {
            get {
                return ResourceManager.GetString("ucRadioCondicionadoLmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ángulo total [º].
        /// </summary>
        public static string uiAbaAnguloTotal {
            get {
                return ResourceManager.GetString("uiAbaAnguloTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grados discretización [º].
        /// </summary>
        public static string uiAbaGradosDiscretizacion {
            get {
                return ResourceManager.GetString("uiAbaGradosDiscretizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalidar tramos con incremento longitud [%].
        /// </summary>
        public static string uiAbaInvalidarTramosIncrementoLongitud {
            get {
                return ResourceManager.GetString("uiAbaInvalidarTramosIncrementoLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tolerancia hacia el punto objetivo [%].
        /// </summary>
        public static string uiAbaToleranciaPuntoObjetivo {
            get {
                return ResourceManager.GetString("uiAbaToleranciaPuntoObjetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discretización tramo [m].
        /// </summary>
        public static string uiAbaTramoDiscretizacion {
            get {
                return ResourceManager.GetString("uiAbaTramoDiscretizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar curvas de gran radio.
        /// </summary>
        public static string uiAplicarGranRadio {
            get {
                return ResourceManager.GetString("uiAplicarGranRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autocorrección.
        /// </summary>
        public static string uiAutocorrecion {
            get {
                return ResourceManager.GetString("uiAutocorrecion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar nombre.
        /// </summary>
        public static string uiBtnCrearNombreSolucion {
            get {
                return ResourceManager.GetString("uiBtnCrearNombreSolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar eje básico....
        /// </summary>
        public static string uiBtnEjeBasico {
            get {
                return ResourceManager.GetString("uiBtnEjeBasico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar eje básico manual.
        /// </summary>
        public static string uiBtnEjeBasicoManual {
            get {
                return ResourceManager.GetString("uiBtnEjeBasicoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar eje básico (punto medio).
        /// </summary>
        public static string uiBtnEjeBasicoPM {
            get {
                return ResourceManager.GetString("uiBtnEjeBasicoPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trazado Tijera.
        /// </summary>
        public static string uiBtnEjeBasicoTijera {
            get {
                return ResourceManager.GetString("uiBtnEjeBasicoTijera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud limitada de recta.
        /// </summary>
        public static string uiChBLongitudLimitada {
            get {
                return ResourceManager.GetString("uiChBLongitudLimitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud máxima de recta.
        /// </summary>
        public static string uiChBLongitudMaxima {
            get {
                return ResourceManager.GetString("uiChBLongitudMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud mínima de recta.
        /// </summary>
        public static string uiChBLongitudMinima {
            get {
                return ResourceManager.GetString("uiChBLongitudMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enlace por clotoides.
        /// </summary>
        public static string uiChBSinRectas {
            get {
                return ResourceManager.GetString("uiChBSinRectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descartar si longitud inferior a:[m].
        /// </summary>
        public static string uiChDescartarAlternCortas {
            get {
                return ResourceManager.GetString("uiChDescartarAlternCortas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente minoración altura máxima pila [0-1].
        /// </summary>
        public static string uiCoeMinAlturaMaximaPila {
            get {
                return ResourceManager.GetString("uiCoeMinAlturaMaximaPila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente minoración altura máxima desmonte [0-1].
        /// </summary>
        public static string uiCoeMinDesmonteAlturaMaxima {
            get {
                return ResourceManager.GetString("uiCoeMinDesmonteAlturaMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente minoración pendiente máxima estructuras [0-1].
        /// </summary>
        public static string uiCoeMinPendienteMaximaEstructuras {
            get {
                return ResourceManager.GetString("uiCoeMinPendienteMaximaEstructuras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente minoración pendiente máxima trazado [0-1].
        /// </summary>
        public static string uiCoeMinPendienteMaximaRoad {
            get {
                return ResourceManager.GetString("uiCoeMinPendienteMaximaRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente minoración altura máxima terraplen [0-1].
        /// </summary>
        public static string uiCoeMinTerraplenAlturaMaxima {
            get {
                return ResourceManager.GetString("uiCoeMinTerraplenAlturaMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear corredores.
        /// </summary>
        public static string uiCorredores {
            get {
                return ResourceManager.GetString("uiCorredores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a \nCreando Secciones.
        /// </summary>
        public static string uiCreandoSecciones {
            get {
                return ResourceManager.GetString("uiCreandoSecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear....
        /// </summary>
        public static string uiCrear {
            get {
                return ResourceManager.GetString("uiCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear informe mediciones.
        /// </summary>
        public static string uiCrearInformeMedicionesSecciones {
            get {
                return ResourceManager.GetString("uiCrearInformeMedicionesSecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distancia [m].
        /// </summary>
        public static string uiDistancia {
            get {
                return ResourceManager.GetString("uiDistancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distancia de entronque [m].
        /// </summary>
        public static string uiDistDistEntronque {
            get {
                return ResourceManager.GetString("uiDistDistEntronque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de pto de entronque desde destino [%].
        /// </summary>
        public static string uiDistDistEntronqueDestinoPC {
            get {
                return ResourceManager.GetString("uiDistDistEntronqueDestinoPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de pto de entronque desde origen [%].
        /// </summary>
        public static string uiDistDistEntronqueOrigenPC {
            get {
                return ResourceManager.GetString("uiDistDistEntronqueOrigenPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Converger a % del punto de inicio y fin.
        /// </summary>
        public static string uiDitanciaEntronquePC {
            get {
                return ResourceManager.GetString("uiDitanciaEntronquePC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eje básico.
        /// </summary>
        public static string uiEjeBasico {
            get {
                return ResourceManager.GetString("uiEjeBasico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eje trazado.
        /// </summary>
        public static string uiEjeTrazado {
            get {
                return ResourceManager.GetString("uiEjeTrazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rotular.
        /// </summary>
        public static string uiEjeTrazadoRotular {
            get {
                return ResourceManager.GetString("uiEjeTrazadoRotular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eje visibilidad.
        /// </summary>
        public static string uiEjeVisibilidad {
            get {
                return ResourceManager.GetString("uiEjeVisibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar eje visibilidad automático.
        /// </summary>
        public static string uiEjeVisibilidadAutomatico {
            get {
                return ResourceManager.GetString("uiEjeVisibilidadAutomatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eje de visibilidad global.
        /// </summary>
        public static string uiEjeVisibilidadGlobal {
            get {
                return ResourceManager.GetString("uiEjeVisibilidadGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear eje de visibilidad global.
        /// </summary>
        public static string uiEjeVisibilidadGlobalCrear {
            get {
                return ResourceManager.GetString("uiEjeVisibilidadGlobalCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar eje visibilidad.
        /// </summary>
        public static string uiEjeVisibilidadUsuario {
            get {
                return ResourceManager.GetString("uiEjeVisibilidadUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo máximo de entronque [seg].
        /// </summary>
        public static string uiEntronqueSegundos {
            get {
                return ResourceManager.GetString("uiEntronqueSegundos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente máxima  [%].
        /// </summary>
        public static string uiEstructurasPendienteMaximaPC {
            get {
                return ResourceManager.GetString("uiEstructurasPendienteMaximaPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente mínima [%].
        /// </summary>
        public static string uiEstructurasPendienteMinimaPC {
            get {
                return ResourceManager.GetString("uiEstructurasPendienteMinimaPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ancho de plataforma [m].
        /// </summary>
        public static string uiEstudioPrevioAnchoPlataforma {
            get {
                return ResourceManager.GetString("uiEstudioPrevioAnchoPlataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste de desmonte [€/m3].
        /// </summary>
        public static string uiEstudioPrevioCosteDesmonte {
            get {
                return ResourceManager.GetString("uiEstudioPrevioCosteDesmonte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste de implantación  [€/m2].
        /// </summary>
        public static string uiEstudioPrevioCosteImplantacion {
            get {
                return ResourceManager.GetString("uiEstudioPrevioCosteImplantacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste de puentes y viaductos [€/m2].
        /// </summary>
        public static string uiEstudioPrevioCostePuentes {
            get {
                return ResourceManager.GetString("uiEstudioPrevioCostePuentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste de terraplén [€/m3].
        /// </summary>
        public static string uiEstudioPrevioCosteTerraplen {
            get {
                return ResourceManager.GetString("uiEstudioPrevioCosteTerraplen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste de túneles [€/Km].
        /// </summary>
        public static string uiEstudioPrevioCosteTuneles {
            get {
                return ResourceManager.GetString("uiEstudioPrevioCosteTuneles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura máxima desmonte [m].
        /// </summary>
        public static string uiEstudioPrevioDesmonteAlturaMaxima {
            get {
                return ResourceManager.GetString("uiEstudioPrevioDesmonteAlturaMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talud desmonte  [t h: 1v].
        /// </summary>
        public static string uiEstudioPrevioDesmonteTalud {
            get {
                return ResourceManager.GetString("uiEstudioPrevioDesmonteTalud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura máxima pila [m].
        /// </summary>
        public static string uiEstudioPrevioPuenteAlturaMaxima {
            get {
                return ResourceManager.GetString("uiEstudioPrevioPuenteAlturaMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura máxima terraplén [m].
        /// </summary>
        public static string uiEstudioPrevioTerraplenAlturaMaxima {
            get {
                return ResourceManager.GetString("uiEstudioPrevioTerraplenAlturaMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talud terraplén [t h: 1v].
        /// </summary>
        public static string uiEstudioPrevioTerraplenTalud {
            get {
                return ResourceManager.GetString("uiEstudioPrevioTerraplenTalud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ferrocarriles.
        /// </summary>
        public static string uiFerrocarriles {
            get {
                return ResourceManager.GetString("uiFerrocarriles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a \nGenerando Mediciones.
        /// </summary>
        public static string uiGenerandoMediciones {
            get {
                return ResourceManager.GetString("uiGenerandoMediciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a \nGenerando Planta.
        /// </summary>
        public static string uiGenerandoPlanta {
            get {
                return ResourceManager.GetString("uiGenerandoPlanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a \nGenerando Secciones.
        /// </summary>
        public static string uiGenerandoSecciones {
            get {
                return ResourceManager.GetString("uiGenerandoSecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar eje básico....
        /// </summary>
        public static string uiGenerarEjeBasico {
            get {
                return ResourceManager.GetString("uiGenerarEjeBasico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración dinámica de trazados.
        /// </summary>
        public static string uiGrAbanico {
            get {
                return ResourceManager.GetString("uiGrAbanico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir tramos.
        /// </summary>
        public static string uiGrAddRectas {
            get {
                return ResourceManager.GetString("uiGrAddRectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Radio [m].
        /// </summary>
        public static string uiGranRadio {
            get {
                return ResourceManager.GetString("uiGranRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Análisis sensibilidad coeficiente minoración.
        /// </summary>
        public static string uiGrCoeficientesMinoracion {
            get {
                return ResourceManager.GetString("uiGrCoeficientesMinoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curvas.
        /// </summary>
        public static string uiGrCurvas {
            get {
                return ResourceManager.GetString("uiGrCurvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estructuras.
        /// </summary>
        public static string uiGrEstructuras {
            get {
                return ResourceManager.GetString("uiGrEstructuras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendientes estructuras (Puentes y túneles).
        /// </summary>
        public static string uiGrEstructurasPendiente {
            get {
                return ResourceManager.GetString("uiGrEstructurasPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costes globales de implantación.
        /// </summary>
        public static string uiGrEstudioPrevioCostesGlobales {
            get {
                return ResourceManager.GetString("uiGrEstudioPrevioCostesGlobales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos geometría.
        /// </summary>
        public static string uiGrEstudioPrevioGeometria {
            get {
                return ResourceManager.GetString("uiGrEstudioPrevioGeometria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendientes de trazado.
        /// </summary>
        public static string uiGrRoadPendientes {
            get {
                return ResourceManager.GetString("uiGrRoadPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos solución.
        /// </summary>
        public static string uiGrSolucion {
            get {
                return ResourceManager.GetString("uiGrSolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        public static string uiGrupo {
            get {
                return ResourceManager.GetString("uiGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ponderación variables para valoración dinámica de trazados.
        /// </summary>
        public static string uiGrValoracion {
            get {
                return ResourceManager.GetString("uiGrValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a \nGuardando Secciones.
        /// </summary>
        public static string uiGuardandoSecciones {
            get {
                return ResourceManager.GetString("uiGuardandoSecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incluir longitud de los tramos.
        /// </summary>
        public static string uiIncluirLongitudTramos {
            get {
                return ResourceManager.GetString("uiIncluirLongitudTramos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Informe....
        /// </summary>
        public static string uiInformeVer {
            get {
                return ResourceManager.GetString("uiInformeVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string uiNombre {
            get {
                return ResourceManager.GetString("uiNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 002_EnvolventeMáxima.
        /// </summary>
        public static string uiNomEnvMaxima {
            get {
                return ResourceManager.GetString("uiNomEnvMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 003_EnvolventeMínima.
        /// </summary>
        public static string uiNomEnvMinima {
            get {
                return ResourceManager.GetString("uiNomEnvMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 001_Primaria.
        /// </summary>
        public static string uiNomSolPrimaria {
            get {
                return ResourceManager.GetString("uiNomSolPrimaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has seleccionado una polilínea.
        /// </summary>
        public static string uiNoSelPolilinea {
            get {
                return ResourceManager.GetString("uiNoSelPolilinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El eje trazado al punto medio solo se puede hacer con avances cortos..
        /// </summary>
        public static string uiObligadoAbanicosCortos {
            get {
                return ResourceManager.GetString("uiObligadoAbanicosCortos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obra lineal.
        /// </summary>
        public static string uiObraLineal {
            get {
                return ResourceManager.GetString("uiObraLineal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        public static string uiObraLinealExport {
            get {
                return ResourceManager.GetString("uiObraLinealExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar planta y secciones.
        /// </summary>
        public static string uiObraLinealExportar {
            get {
                return ResourceManager.GetString("uiObraLinealExportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Penalizar alternativa convergencia por incumplimiento de normativa en tramos cortos.
        /// </summary>
        public static string uiPenalizarTramosCortos {
            get {
                return ResourceManager.GetString("uiPenalizarTramosCortos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente máxima – filtro cotas.
        /// </summary>
        public static string uiPendMaxFiltroCotas {
            get {
                return ResourceManager.GetString("uiPendMaxFiltroCotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente máxima – filtro terreno.
        /// </summary>
        public static string uiPendMaxFiltroTerreno {
            get {
                return ResourceManager.GetString("uiPendMaxFiltroTerreno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peralte [%].
        /// </summary>
        public static string uiPeraltePC {
            get {
                return ResourceManager.GetString("uiPeraltePC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil longitudinal.
        /// </summary>
        public static string uiPerfilLongitudinal {
            get {
                return ResourceManager.GetString("uiPerfilLongitudinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Planta.
        /// </summary>
        public static string uiPlanta {
            get {
                return ResourceManager.GetString("uiPlanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar puentes y viaductos.
        /// </summary>
        public static string uiPuenteGenerar {
            get {
                return ResourceManager.GetString("uiPuenteGenerar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº max de repeticiones.
        /// </summary>
        public static string uiRepetionesMax {
            get {
                return ResourceManager.GetString("uiRepetionesMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Considerar Aij constante.
        /// </summary>
        public static string uiRoadAijConsiderarConstante {
            get {
                return ResourceManager.GetString("uiRoadAijConsiderarConstante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aij máximo tramo [m].
        /// </summary>
        public static string uiRoadAijMaximo {
            get {
                return ResourceManager.GetString("uiRoadAijMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aij mínimo tramo [m].
        /// </summary>
        public static string uiRoadAijMinimo {
            get {
                return ResourceManager.GetString("uiRoadAijMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avance máximo.
        /// </summary>
        public static string uiRoadAvanceMaximo {
            get {
                return ResourceManager.GetString("uiRoadAvanceMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        public static string uiRoadGrupo {
            get {
                return ResourceManager.GetString("uiRoadGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kv cóncavo.
        /// </summary>
        public static string uiRoadKvConcavo {
            get {
                return ResourceManager.GetString("uiRoadKvConcavo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kv convexo.
        /// </summary>
        public static string uiRoadKvConvexo {
            get {
                return ResourceManager.GetString("uiRoadKvConvexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deseable.
        /// </summary>
        public static string uiRoadKvDeseable {
            get {
                return ResourceManager.GetString("uiRoadKvDeseable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo.
        /// </summary>
        public static string uiRoadKvMinimo {
            get {
                return ResourceManager.GetString("uiRoadKvMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente máxima trazado [%].
        /// </summary>
        public static string uiRoadPendienteMaximaPC {
            get {
                return ResourceManager.GetString("uiRoadPendienteMaximaPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente mínima trazado [%].
        /// </summary>
        public static string uiRoadPendienteMinimaPC {
            get {
                return ResourceManager.GetString("uiRoadPendienteMinimaPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permitir reducciones puntuales velocidad.
        /// </summary>
        public static string uiRoadPermitirReduccionesVelocidad {
            get {
                return ResourceManager.GetString("uiRoadPermitirReduccionesVelocidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferencias [Rectas\Curvas].
        /// </summary>
        public static string uiRoadPreferencias {
            get {
                return ResourceManager.GetString("uiRoadPreferencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curvas.
        /// </summary>
        public static string uiRoadPreferenciasCurvas {
            get {
                return ResourceManager.GetString("uiRoadPreferenciasCurvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferencias Kv.
        /// </summary>
        public static string uiRoadPreferenciasKv {
            get {
                return ResourceManager.GetString("uiRoadPreferenciasKv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rectas.
        /// </summary>
        public static string uiRoadPreferenciasRectas {
            get {
                return ResourceManager.GetString("uiRoadPreferenciasRectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Radio proyecto [m].
        /// </summary>
        public static string uiRoadRadio {
            get {
                return ResourceManager.GetString("uiRoadRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar carretera.
        /// </summary>
        public static string uiRoadSelect {
            get {
                return ResourceManager.GetString("uiRoadSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor mínimo salida-llegada [m].
        /// </summary>
        public static string uiRoadValorMinimoSalidaLlegada {
            get {
                return ResourceManager.GetString("uiRoadValorMinimoSalidaLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Velocidad proyecto [km/h].
        /// </summary>
        public static string uiRoadVelocidad {
            get {
                return ResourceManager.GetString("uiRoadVelocidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rotular....
        /// </summary>
        public static string uiRotular {
            get {
                return ResourceManager.GetString("uiRotular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Sección.
        /// </summary>
        public static string uiSeccion {
            get {
                return ResourceManager.GetString("uiSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección.
        /// </summary>
        public static string uiSeleccion {
            get {
                return ResourceManager.GetString("uiSeleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona Eje Visibilidad.
        /// </summary>
        public static string uiSeleccionaEjeVisibilidad {
            get {
                return ResourceManager.GetString("uiSeleccionaEjeVisibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el tramo ganador.
        /// </summary>
        public static string uiSelTramoGanador {
            get {
                return ResourceManager.GetString("uiSelTramoGanador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Separación para carreteras.
        /// </summary>
        public static string uiSeparacionCarreteras {
            get {
                return ResourceManager.GetString("uiSeparacionCarreteras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Separación para ferrocarriles.
        /// </summary>
        public static string uiSeparacionFerrocarril {
            get {
                return ResourceManager.GetString("uiSeparacionFerrocarril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar envolvente máxima-mínima.
        /// </summary>
        public static string uiSolucionGenerarEnvolventeMaxMin {
            get {
                return ResourceManager.GetString("uiSolucionGenerarEnvolventeMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string uiSolucionNombre {
            get {
                return ResourceManager.GetString("uiSolucionNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avances cortos.
        /// </summary>
        public static string uiSolucionOptAvancesCortos {
            get {
                return ResourceManager.GetString("uiSolucionOptAvancesCortos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avances largos.
        /// </summary>
        public static string uiSolucionOptAvancesLargos {
            get {
                return ResourceManager.GetString("uiSolucionOptAvancesLargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carretera.
        /// </summary>
        public static string uiTabCarretera {
            get {
                return ResourceManager.GetString("uiTabCarretera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Geometría y costes.
        /// </summary>
        public static string uiTabEstudioPrevio {
            get {
                return ResourceManager.GetString("uiTabEstudioPrevio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opc. Avanzadas 1.
        /// </summary>
        public static string uiTabOptAvanzadas1 {
            get {
                return ResourceManager.GetString("uiTabOptAvanzadas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opc. Avanzadas 2.
        /// </summary>
        public static string uiTabOptAvanzadas2 {
            get {
                return ResourceManager.GetString("uiTabOptAvanzadas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendientes.
        /// </summary>
        public static string uiTabPendientes {
            get {
                return ResourceManager.GetString("uiTabPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tijera.
        /// </summary>
        public static string uiTabTijera {
            get {
                return ResourceManager.GetString("uiTabTijera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración.
        /// </summary>
        public static string uiTabValoracion {
            get {
                return ResourceManager.GetString("uiTabValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar túneles.
        /// </summary>
        public static string uiTunelesGenerar {
            get {
                return ResourceManager.GetString("uiTunelesGenerar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración por coste global [%].
        /// </summary>
        public static string uiValoracionCostesPC {
            get {
                return ResourceManager.GetString("uiValoracionCostesPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración por distancia [%].
        /// </summary>
        public static string uiValoracionDistanciaPC {
            get {
                return ResourceManager.GetString("uiValoracionDistanciaPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración por orografía de implantación [%].
        /// </summary>
        public static string uiValoracionPendientePC {
            get {
                return ResourceManager.GetString("uiValoracionPendientePC", resourceCulture);
            }
        }
    }
}
