//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tadLayLan.Tdi {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strFrmValoracion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strFrmValoracion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tadLayLan.Tdi.strFrmValoracion", typeof(strFrmValoracion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acuiferos [%].
        /// </summary>
        public static string uiAcuiferos {
            get {
                return ResourceManager.GetString("uiAcuiferos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador de valoración de alternativas.
        /// </summary>
        public static string uiAdminValoracion {
            get {
                return ResourceManager.GetString("uiAdminValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprovechamientos [%].
        /// </summary>
        public static string uiAprovechamientos {
            get {
                return ResourceManager.GetString("uiAprovechamientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos visuales [%].
        /// </summary>
        public static string uiCamposVisuales {
            get {
                return ResourceManager.GetString("uiCamposVisuales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor de CBR [%].
        /// </summary>
        public static string uiCBR {
            get {
                return ResourceManager.GetString("uiCBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cimentación de estructuras [%].
        /// </summary>
        public static string uiCimEst {
            get {
                return ResourceManager.GetString("uiCimEst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cimentación obras menores [%].
        /// </summary>
        public static string uiCimObrasMenores {
            get {
                return ResourceManager.GetString("uiCimObrasMenores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compensación de tierras  [%].
        /// </summary>
        public static string uiCompensacionTierras {
            get {
                return ResourceManager.GetString("uiCompensacionTierras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cruce infraestructuras lineales [%].
        /// </summary>
        public static string uiCruceInfra {
            get {
                return ResourceManager.GetString("uiCruceInfra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cruces vías pecuarias [%].
        /// </summary>
        public static string uiCruceViasPecuarias {
            get {
                return ResourceManager.GetString("uiCruceViasPecuarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Climática [%].
        /// </summary>
        public static string uiDgvClimatica {
            get {
                return ResourceManager.GetString("uiDgvClimatica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string uiDgvDescripcion {
            get {
                return ResourceManager.GetString("uiDgvDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Económicas [%].
        /// </summary>
        public static string uiDgvEconomicas {
            get {
                return ResourceManager.GetString("uiDgvEconomicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estructuras, túneles y muros [%].
        /// </summary>
        public static string uiDgvEstructurasTunelesMuros {
            get {
                return ResourceManager.GetString("uiDgvEstructurasTunelesMuros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Geotecnia [%].
        /// </summary>
        public static string uiDgvGeotecnia {
            get {
                return ResourceManager.GetString("uiDgvGeotecnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado hipótesis.
        /// </summary>
        public static string uiDgvHipotesis {
            get {
                return ResourceManager.GetString("uiDgvHipotesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medioambiental [%].
        /// </summary>
        public static string uiDgvMedioambiental {
            get {
                return ResourceManager.GetString("uiDgvMedioambiental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patrimoniales [%].
        /// </summary>
        public static string uiDgvPatrimoniales {
            get {
                return ResourceManager.GetString("uiDgvPatrimoniales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Socioeconómicas [%].
        /// </summary>
        public static string uiDgvSocioEconomicas {
            get {
                return ResourceManager.GetString("uiDgvSocioEconomicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trazado [%].
        /// </summary>
        public static string uiDgvTrazado {
            get {
                return ResourceManager.GetString("uiDgvTrazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dominio público hidráulico [%].
        /// </summary>
        public static string uiDominioPublicoHidraulico {
            get {
                return ResourceManager.GetString("uiDominioPublicoHidraulico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estabilidad de taludes [%].
        /// </summary>
        public static string uiEstabilidadTalud {
            get {
                return ResourceManager.GetString("uiEstabilidadTalud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estabilidad horizontal terreno [%].
        /// </summary>
        public static string uiEstabilidadTerreno {
            get {
                return ResourceManager.GetString("uiEstabilidadTerreno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excavabilidad [%].
        /// </summary>
        public static string uiExcavailidad {
            get {
                return ResourceManager.GetString("uiExcavailidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fauna [%].
        /// </summary>
        public static string uiFauna {
            get {
                return ResourceManager.GetString("uiFauna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flora [%].
        /// </summary>
        public static string uiFlora {
            get {
                return ResourceManager.GetString("uiFlora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado soluciones Valoradas por Hipótesis.
        /// </summary>
        public static string uiFrmHipotesisSoluciones {
            get {
                return ResourceManager.GetString("uiFrmHipotesisSoluciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editor de hipótesis.
        /// </summary>
        public static string uiFrmMatrizDecisionDetail {
            get {
                return ResourceManager.GetString("uiFrmMatrizDecisionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zonas fuertes heladas [%].
        /// </summary>
        public static string uiFuertesHeladas {
            get {
                return ResourceManager.GetString("uiFuertesHeladas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zonas fuertes vientos [%].
        /// </summary>
        public static string uiFuertesVientos {
            get {
                return ResourceManager.GetString("uiFuertesVientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Geotecnia de estructuras [%].
        /// </summary>
        public static string uiGeoEst {
            get {
                return ResourceManager.GetString("uiGeoEst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Geotecnica de túneles [%].
        /// </summary>
        public static string uiGeoTun {
            get {
                return ResourceManager.GetString("uiGeoTun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cálculo de hipótesis.
        /// </summary>
        public static string uiGrCalculoHipotesis {
            get {
                return ResourceManager.GetString("uiGrCalculoHipotesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución de valoraciones.
        /// </summary>
        public static string uiGrDisVal {
            get {
                return ResourceManager.GetString("uiGrDisVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos.
        /// </summary>
        public static string uiGrHipotesisDatos {
            get {
                return ResourceManager.GetString("uiGrHipotesisDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Áreas de valoración.
        /// </summary>
        public static string uiGrHipotesisValoraciones {
            get {
                return ResourceManager.GetString("uiGrHipotesisValoraciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución valoraciones parte pública.
        /// </summary>
        public static string uiGrInversionEstatal {
            get {
                return ResourceManager.GetString("uiGrInversionEstatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución Valoraciones parte privada.
        /// </summary>
        public static string uiGrInversionPrivada {
            get {
                return ResourceManager.GetString("uiGrInversionPrivada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Capitulos Valorados.
        /// </summary>
        public static string uiGrLstCapitulosValorados {
            get {
                return ResourceManager.GetString("uiGrLstCapitulosValorados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Soluciones Valoradas.
        /// </summary>
        public static string uiGrLstSolucionesValoradas {
            get {
                return ResourceManager.GetString("uiGrLstSolucionesValoradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de SubCapitulos Valorados.
        /// </summary>
        public static string uiGrLstSubcapitulosValorados {
            get {
                return ResourceManager.GetString("uiGrLstSubcapitulosValorados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ponderación de valoraciones.
        /// </summary>
        public static string uiGrPonderacionValoraciones {
            get {
                return ResourceManager.GetString("uiGrPonderacionValoraciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración de geotecnia de estructuras.
        /// </summary>
        public static string uiGrValGeoEst {
            get {
                return ResourceManager.GetString("uiGrValGeoEst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración de geotecnia de túneles.
        /// </summary>
        public static string uiGrValGeoTun {
            get {
                return ResourceManager.GetString("uiGrValGeoTun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración global de estructuras y túneles.
        /// </summary>
        public static string uiGrValGlobal {
            get {
                return ResourceManager.GetString("uiGrValGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado soluciones disponibles para valoración.
        /// </summary>
        public static string uiGrValoracionSoluciones {
            get {
                return ResourceManager.GetString("uiGrValoracionSoluciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matriz de decisión.
        /// </summary>
        public static string uiHeaderMatrizDecision {
            get {
                return ResourceManager.GetString("uiHeaderMatrizDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hipótesis.
        /// </summary>
        public static string uiHipotesis {
            get {
                return ResourceManager.GetString("uiHipotesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interés paisajístico [%].
        /// </summary>
        public static string uiInteresPaisajistico {
            get {
                return ResourceManager.GetString("uiInteresPaisajistico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zonas de lluvias intensas [%].
        /// </summary>
        public static string uiLluviasIntensas {
            get {
                return ResourceManager.GetString("uiLluviasIntensas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Métodos excavación [%].
        /// </summary>
        public static string uiMetodosExcavacion {
            get {
                return ResourceManager.GetString("uiMetodosExcavacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Montes públicos [%].
        /// </summary>
        public static string uiMontesPublicos {
            get {
                return ResourceManager.GetString("uiMontesPublicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muros [%].
        /// </summary>
        public static string uiMuros {
            get {
                return ResourceManager.GetString("uiMuros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zonas de nevadas [%].
        /// </summary>
        public static string uiNevadas {
            get {
                return ResourceManager.GetString("uiNevadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zonas nieblas densas [%].
        /// </summary>
        public static string uiNieblasDensas {
            get {
                return ResourceManager.GetString("uiNieblasDensas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permeabilidad fauna [%].
        /// </summary>
        public static string uiPermeabilidadFauna {
            get {
                return ResourceManager.GetString("uiPermeabilidadFauna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presencia agua [%].
        /// </summary>
        public static string uiPresenciaAgua {
            get {
                return ResourceManager.GetString("uiPresenciaAgua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a B/C Explotación privada [%].
        /// </summary>
        public static string uiPrivadaBC {
            get {
                return ResourceManager.GetString("uiPrivadaBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inversión privada [%].
        /// </summary>
        public static string uiPrivadaPresupuesto {
            get {
                return ResourceManager.GetString("uiPrivadaPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a V.A.N.  Explotación privada [%].
        /// </summary>
        public static string uiPrivadaVAN {
            get {
                return ResourceManager.GetString("uiPrivadaVAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedimiento excavación cimientos [%].
        /// </summary>
        public static string uiProExcavacionCimientos {
            get {
                return ResourceManager.GetString("uiProExcavacionCimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Protección de taludes [%].
        /// </summary>
        public static string uiProteccionTalud {
            get {
                return ResourceManager.GetString("uiProteccionTalud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a B/C rentabilidad social [%].
        /// </summary>
        public static string uiPublicoBC {
            get {
                return ResourceManager.GetString("uiPublicoBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inversión pública [%].
        /// </summary>
        public static string uiPublicoPresupuesto {
            get {
                return ResourceManager.GetString("uiPublicoPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a V.A.N. Rentabilidad social [%].
        /// </summary>
        public static string uiPublicoVAN {
            get {
                return ResourceManager.GetString("uiPublicoVAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RMR [%].
        /// </summary>
        public static string uiRmr {
            get {
                return ResourceManager.GetString("uiRmr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector primario [%].
        /// </summary>
        public static string uiSectorPrimario {
            get {
                return ResourceManager.GetString("uiSectorPrimario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector secundario [%].
        /// </summary>
        public static string uiSectorSecundario {
            get {
                return ResourceManager.GetString("uiSectorSecundario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector terciario [%].
        /// </summary>
        public static string uiSectorTerciario {
            get {
                return ResourceManager.GetString("uiSectorTerciario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suelos [%].
        /// </summary>
        public static string uiSuelos {
            get {
                return ResourceManager.GetString("uiSuelos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suelos no urbanizables [%].
        /// </summary>
        public static string uiSuelosNoUrbanizables {
            get {
                return ResourceManager.GetString("uiSuelosNoUrbanizables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suelos urbanizables [%].
        /// </summary>
        public static string uiSuelosUrbanizables {
            get {
                return ResourceManager.GetString("uiSuelosUrbanizables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suelos urbanos [%].
        /// </summary>
        public static string uiSuelosUrbanos {
            get {
                return ResourceManager.GetString("uiSuelosUrbanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo recorrido [%].
        /// </summary>
        public static string uiTiempoRecorrido {
            get {
                return ResourceManager.GetString("uiTiempoRecorrido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zonas de tormentas frecuentes [%].
        /// </summary>
        public static string uiTormentasFrecuentes {
            get {
                return ResourceManager.GetString("uiTormentasFrecuentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tratamientos específicos [%].
        /// </summary>
        public static string uiTratamientosEspecificos {
            get {
                return ResourceManager.GetString("uiTratamientosEspecificos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trazado en alzado [%].
        /// </summary>
        public static string uiTrazadoAlzado {
            get {
                return ResourceManager.GetString("uiTrazadoAlzado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trazado en planta [%].
        /// </summary>
        public static string uiTrazadoPlanta {
            get {
                return ResourceManager.GetString("uiTrazadoPlanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de tuneladora [%].
        /// </summary>
        public static string uiTunTipoTuneladora {
            get {
                return ResourceManager.GetString("uiTunTipoTuneladora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zonas de umbria [%].
        /// </summary>
        public static string uiUmbria {
            get {
                return ResourceManager.GetString("uiUmbria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración estructuras y túneles.
        /// </summary>
        public static string uiVAESTU {
            get {
                return ResourceManager.GetString("uiVAESTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración afecciones climáticas.
        /// </summary>
        public static string uiVALCLI {
            get {
                return ResourceManager.GetString("uiVALCLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración variables económicas.
        /// </summary>
        public static string uiVALECO {
            get {
                return ResourceManager.GetString("uiVALECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración de la geotecnia.
        /// </summary>
        public static string uiVALGEO {
            get {
                return ResourceManager.GetString("uiVALGEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matriz de decisión.
        /// </summary>
        public static string uiVALMAT {
            get {
                return ResourceManager.GetString("uiVALMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración medioambienal.
        /// </summary>
        public static string uiVALMED {
            get {
                return ResourceManager.GetString("uiVALMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valorar Soluciones por Hipótesis.
        /// </summary>
        public static string uiValorarSolucionesPorHipotesis {
            get {
                return ResourceManager.GetString("uiValorarSolucionesPorHipotesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración variables patrimoniales.
        /// </summary>
        public static string uiVALPAT {
            get {
                return ResourceManager.GetString("uiVALPAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración variables socioeconómicas.
        /// </summary>
        public static string uiVALSOC {
            get {
                return ResourceManager.GetString("uiVALSOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración del trazado.
        /// </summary>
        public static string uiVALTRA {
            get {
                return ResourceManager.GetString("uiVALTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen movimiento tierras [%].
        /// </summary>
        public static string uiVolumenMovTierras {
            get {
                return ResourceManager.GetString("uiVolumenMovTierras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yacimientos arqueológicos [%].
        /// </summary>
        public static string uiYacimientosArqueologicos {
            get {
                return ResourceManager.GetString("uiYacimientosArqueologicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zonas especial interés [%].
        /// </summary>
        public static string uiZonasEspecialInteres {
            get {
                return ResourceManager.GetString("uiZonasEspecialInteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zonas de infraestructuras públicas [%].
        /// </summary>
        public static string uiZonasInfraPublicas {
            get {
                return ResourceManager.GetString("uiZonasInfraPublicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zonas minas y canteras [%].
        /// </summary>
        public static string uiZonasMinasCanteras {
            get {
                return ResourceManager.GetString("uiZonasMinasCanteras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zonas protección [%].
        /// </summary>
        public static string uiZonProteccion {
            get {
                return ResourceManager.GetString("uiZonProteccion", resourceCulture);
            }
        }
    }
}
