//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tadLayLan.Tdi {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strFrmEstilosEjePerfil {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strFrmEstilosEjePerfil() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tadLayLan.Tdi.strFrmEstilosEjePerfil", typeof(strFrmEstilosEjePerfil).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estilo alineación  objeto.
        /// </summary>
        public static string uiEstiloEjeTrazado {
            get {
                return ResourceManager.GetString("uiEstiloEjeTrazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estilo alineación  etiquetas.
        /// </summary>
        public static string uiEstiloEjeTrazadoEtiquetas {
            get {
                return ResourceManager.GetString("uiEstiloEjeTrazadoEtiquetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estilo perfil etiquetas.
        /// </summary>
        public static string uiEstiloPerfilEtiquetas {
            get {
                return ResourceManager.GetString("uiEstiloPerfilEtiquetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estilo perfil objeto.
        /// </summary>
        public static string uiEstiloPerfilObjeto {
            get {
                return ResourceManager.GetString("uiEstiloPerfilObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estilo visualización guitarra.
        /// </summary>
        public static string uiEstiloVisualizacionGuitarra {
            get {
                return ResourceManager.GetString("uiEstiloVisualizacionGuitarra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estilo visualización perfil.
        /// </summary>
        public static string uiEstiloVisualizacionPerfil {
            get {
                return ResourceManager.GetString("uiEstiloVisualizacionPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definir estilos eje trazado.
        /// </summary>
        public static string uiGrEjeEstilos {
            get {
                return ResourceManager.GetString("uiGrEjeEstilos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definir estilos perfil longitudinal.
        /// </summary>
        public static string uiGrPerfilEstilos {
            get {
                return ResourceManager.GetString("uiGrPerfilEstilos", resourceCulture);
            }
        }
    }
}
