//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tadLayLan.Tdb {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strFrmGisGeo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strFrmGisGeo() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tadLayLan.Tdb.strFrmGisGeo", typeof(strFrmGisGeo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capas de arcén.
        /// </summary>
        public static string uiARC {
            get {
                return ResourceManager.GetString("uiARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capas de asiento.
        /// </summary>
        public static string uiASI {
            get {
                return ResourceManager.GetString("uiASI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capas de berma.
        /// </summary>
        public static string uiBER {
            get {
                return ResourceManager.GetString("uiBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar con berma al pie.
        /// </summary>
        public static string uiBermaPie {
            get {
                return ResourceManager.GetString("uiBermaPie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor de (a) [m].
        /// </summary>
        public static string uiBermaX {
            get {
                return ResourceManager.GetString("uiBermaX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor de (h) [m].
        /// </summary>
        public static string uiBermaY {
            get {
                return ResourceManager.GetString("uiBermaY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar capa de firme a capa de arcén.
        /// </summary>
        public static string uiBtnCopiarFirmeViario {
            get {
                return ResourceManager.GetString("uiBtnCopiarFirmeViario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material capas asiento.
        /// </summary>
        public static string uiCapaAsientoMaterial {
            get {
                return ResourceManager.GetString("uiCapaAsientoMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprovechamiento para capas de asiento  [%].
        /// </summary>
        public static string uiCapaAsientoRendimientoPC {
            get {
                return ResourceManager.GetString("uiCapaAsientoRendimientoPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Válido para capas de asiento?.
        /// </summary>
        public static string uiCapaAsientoValido {
            get {
                return ResourceManager.GetString("uiCapaAsientoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprovechamiento fabricación material granular  [%].
        /// </summary>
        public static string uiCapaFirmeRendimiento {
            get {
                return ResourceManager.GetString("uiCapaFirmeRendimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprovechamiento para capas granulares de firme  [%].
        /// </summary>
        public static string uiCapaGranularesRendimientoPC {
            get {
                return ResourceManager.GetString("uiCapaGranularesRendimientoPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona de berma.
        /// </summary>
        public static string uiCapasBerma {
            get {
                return ResourceManager.GetString("uiCapasBerma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has configurado el listado de capas de firme, asiento o arcén.
        /// </summary>
        public static string uiCapasCountCero {
            get {
                return ResourceManager.GetString("uiCapasCountCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error / El valor de la zona es nulo.
        /// </summary>
        public static string uiCapasIdNull {
            get {
                return ResourceManager.GetString("uiCapasIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para poder asignar las capas, debes guardar el registro actual.
        /// </summary>
        public static string uiCapasMustSave {
            get {
                return ResourceManager.GetString("uiCapasMustSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CBR.
        /// </summary>
        public static string uiCBR {
            get {
                return ResourceManager.GetString("uiCBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente esponjamiento.
        /// </summary>
        public static string uiCoeficienteEsponjamiento {
            get {
                return ResourceManager.GetString("uiCoeficienteEsponjamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente paso a terraplén.
        /// </summary>
        public static string uiCoeficientePasoTerraplen {
            get {
                return ResourceManager.GetString("uiCoeficientePasoTerraplen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        public static string uiColor {
            get {
                return ResourceManager.GetString("uiColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayudas.
        /// </summary>
        public static string uiCopiarFirmeArcen {
            get {
                return ResourceManager.GetString("uiCopiarFirmeArcen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desbroce espesor [m].
        /// </summary>
        public static string uiDesbroceEspesor {
            get {
                return ResourceManager.GetString("uiDesbroceEspesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material desbroce.
        /// </summary>
        public static string uiDesbroceMaterial {
            get {
                return ResourceManager.GetString("uiDesbroceMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura máxima de muro (H) [m].
        /// </summary>
        public static string uiDesmonteMuroHmax {
            get {
                return ResourceManager.GetString("uiDesmonteMuroHmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle.
        /// </summary>
        public static string uiDetalle {
            get {
                return ResourceManager.GetString("uiDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espesor [m].
        /// </summary>
        public static string uiEspesor {
            get {
                return ResourceManager.GetString("uiEspesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espesor Total : {0} [m].
        /// </summary>
        public static string uiEspesorTotal {
            get {
                return ResourceManager.GetString("uiEspesorTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excavación con empleo de martillo neumático o similar.
        /// </summary>
        public static string uiExcaMartillo {
            get {
                return ResourceManager.GetString("uiExcaMartillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excavación medios convencionales .
        /// </summary>
        public static string uiExcaMediosConvencionales {
            get {
                return ResourceManager.GetString("uiExcaMediosConvencionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excavación con empleo de sistemas de agotamiento del nivel freático .
        /// </summary>
        public static string uiExcaNivelFreatico {
            get {
                return ResourceManager.GetString("uiExcaNivelFreatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excavabilidad.
        /// </summary>
        public static string uiExcavabilidad {
            get {
                return ResourceManager.GetString("uiExcavabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material excavación.
        /// </summary>
        public static string uiExcavacionMaterial {
            get {
                return ResourceManager.GetString("uiExcavacionMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente aprovechamiento para terraplén [%].
        /// </summary>
        public static string uiExcavacionTerraplenPC {
            get {
                return ResourceManager.GetString("uiExcavacionTerraplenPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excavación con retirada a vertedero en dos fases.
        /// </summary>
        public static string uiExcaVertedero2Fases {
            get {
                return ResourceManager.GetString("uiExcaVertedero2Fases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excavación con voladuras.
        /// </summary>
        public static string uiExcaVoladuras {
            get {
                return ResourceManager.GetString("uiExcaVoladuras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capas de firme.
        /// </summary>
        public static string uiFIR {
            get {
                return ResourceManager.GetString("uiFIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material granular.
        /// </summary>
        public static string uiFirmeMaterial {
            get {
                return ResourceManager.GetString("uiFirmeMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado zonas geotécnicas.
        /// </summary>
        public static string uiGrListadosZonas {
            get {
                return ResourceManager.GetString("uiGrListadosZonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo geológico.
        /// </summary>
        public static string uiGrupoGeologico {
            get {
                return ResourceManager.GetString("uiGrupoGeologico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo litológico.
        /// </summary>
        public static string uiGrupoLitologico {
            get {
                return ResourceManager.GetString("uiGrupoLitologico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Grupo?.
        /// </summary>
        public static string uiIndicaGrupo {
            get {
                return ResourceManager.GetString("uiIndicaGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Nombre?.
        /// </summary>
        public static string uiIndicaNombre {
            get {
                return ResourceManager.GetString("uiIndicaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indica un valor.
        /// </summary>
        public static string uiIndicaValor {
            get {
                return ResourceManager.GetString("uiIndicaValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar saneamiento desmonte.
        /// </summary>
        public static string uiIsSaneoDesmonte {
            get {
                return ResourceManager.GetString("uiIsSaneoDesmonte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar saneamiento terraplén.
        /// </summary>
        public static string uiIsSaneoTerraplen {
            get {
                return ResourceManager.GetString("uiIsSaneoTerraplen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ficha geotécnica - Movimiento de tierras.
        /// </summary>
        public static string uiLblFrm {
            get {
                return ResourceManager.GetString("uiLblFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador de fichas geotécnicas ; Movimiento de tierras.
        /// </summary>
        public static string uiLblFrmManager {
            get {
                return ResourceManager.GetString("uiLblFrmManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material.
        /// </summary>
        public static string uiMaterial {
            get {
                return ResourceManager.GetString("uiMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material del muro.
        /// </summary>
        public static string uiMaterialMuro {
            get {
                return ResourceManager.GetString("uiMaterialMuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empotramiento [m].
        /// </summary>
        public static string uiMuroEmpotramiento {
            get {
                return ResourceManager.GetString("uiMuroEmpotramiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espesor medio del muro [m].
        /// </summary>
        public static string uiMuroEspesor {
            get {
                return ResourceManager.GetString("uiMuroEspesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden.
        /// </summary>
        public static string uiOrden {
            get {
                return ResourceManager.GetString("uiOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente máxima terreno recomendable [%].
        /// </summary>
        public static string uiPendienteMaximaTerreno {
            get {
                return ResourceManager.GetString("uiPendienteMaximaTerreno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material saneamiento en desmonte.
        /// </summary>
        public static string uiSaneoDesmonteCode {
            get {
                return ResourceManager.GetString("uiSaneoDesmonteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espesor saneamiento en desmonte [m].
        /// </summary>
        public static string uiSaneoDesmonteEspesor {
            get {
                return ResourceManager.GetString("uiSaneoDesmonteEspesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura escalón [m].
        /// </summary>
        public static string uiSaneoTerraplenAlturaEscalon {
            get {
                return ResourceManager.GetString("uiSaneoTerraplenAlturaEscalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material saneamiento en terraplén.
        /// </summary>
        public static string uiSaneoTerraplenCode {
            get {
                return ResourceManager.GetString("uiSaneoTerraplenCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espesor saneamiento en terraplén [m].
        /// </summary>
        public static string uiSaneoTerraplenEspesor {
            get {
                return ResourceManager.GetString("uiSaneoTerraplenEspesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente máxima sin escalón [%].
        /// </summary>
        public static string uiSaneoTerraplenPendMaxSinEscalon {
            get {
                return ResourceManager.GetString("uiSaneoTerraplenPendMaxSinEscalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capas.
        /// </summary>
        public static string uiTabCapas {
            get {
                return ResourceManager.GetString("uiTabCapas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos generales.
        /// </summary>
        public static string uiTabDatos {
            get {
                return ResourceManager.GetString("uiTabDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desmonte.
        /// </summary>
        public static string uiTabDesmonte {
            get {
                return ResourceManager.GetString("uiTabDesmonte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excavabilidad y protecciones de talud.
        /// </summary>
        public static string uiTabExcPro {
            get {
                return ResourceManager.GetString("uiTabExcPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terraplén.
        /// </summary>
        public static string uiTabTerraplen {
            get {
                return ResourceManager.GetString("uiTabTerraplen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talud [Th: 1v].
        /// </summary>
        public static string uiTalud {
            get {
                return ResourceManager.GetString("uiTalud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura máxima eje [m].
        /// </summary>
        public static string uiTaludAlturaMaxEje {
            get {
                return ResourceManager.GetString("uiTaludAlturaMaxEje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talud con bermas.
        /// </summary>
        public static string uiTaludBermas {
            get {
                return ResourceManager.GetString("uiTaludBermas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Constante.
        /// </summary>
        public static string uiTaludConstante {
            get {
                return ResourceManager.GetString("uiTaludConstante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muro en margen.
        /// </summary>
        public static string uiTaludDesMur {
            get {
                return ResourceManager.GetString("uiTaludDesMur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Protecciones talud.
        /// </summary>
        public static string uiTaludProtecciones {
            get {
                return ResourceManager.GetString("uiTaludProtecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Taludes con protección flexible.
        /// </summary>
        public static string uiTaludProtecFlexibles {
            get {
                return ResourceManager.GetString("uiTaludProtecFlexibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Taludes con protecciones rígidas y/o anclajes.
        /// </summary>
        public static string uiTaludProtecRigidas {
            get {
                return ResourceManager.GetString("uiTaludProtecRigidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Taludes sin protección.
        /// </summary>
        public static string uiTaludProtecSin {
            get {
                return ResourceManager.GetString("uiTaludProtecSin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talud sobre muro.
        /// </summary>
        public static string uiTaludTerMuro {
            get {
                return ResourceManager.GetString("uiTaludTerMuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material terraplén.
        /// </summary>
        public static string uiTerraplenMaterial {
            get {
                return ResourceManager.GetString("uiTerraplenMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura máxima de talud (H) [m].
        /// </summary>
        public static string uiTerraplenMuroHmax {
            get {
                return ResourceManager.GetString("uiTerraplenMuroHmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TNS.
        /// </summary>
        public static string uiTNS {
            get {
                return ResourceManager.GetString("uiTNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La suma de los porcentajes de excavabilidad no es 100.
        /// </summary>
        public static string uiUserExcavabilidadNot100 {
            get {
                return ResourceManager.GetString("uiUserExcavabilidadNot100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La suma de los porcentajes de protección de talud no es 100.
        /// </summary>
        public static string uiUserTaludProteccioNot100 {
            get {
                return ResourceManager.GetString("uiUserTaludProteccioNot100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se puede definir una zona general.
        /// </summary>
        public static string uiUserZonaGeneralIsMayor1 {
            get {
                return ResourceManager.GetString("uiUserZonaGeneralIsMayor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes definir una zona general.
        /// </summary>
        public static string uiUserZonaGeneralIsZero {
            get {
                return ResourceManager.GetString("uiUserZonaGeneralIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración subjetiva procedimientos excavación.
        /// </summary>
        public static string uiValoracionExcavabilidad {
            get {
                return ResourceManager.GetString("uiValoracionExcavabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración subjetiva protecciones de talud.
        /// </summary>
        public static string uiValoracionTaludProtecciones {
            get {
                return ResourceManager.GetString("uiValoracionTaludProtecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Válido para Zahorras?.
        /// </summary>
        public static string uiZahorrasValido {
            get {
                return ResourceManager.GetString("uiZahorrasValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona movimiento tierras general.
        /// </summary>
        public static string uiZonaDefault {
            get {
                return ResourceManager.GetString("uiZonaDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los coeficientes de aprovechamiento no están correctamente configurados.
        ///(Capa terraplén &gt; Capa asiento &gt; Capa granular).
        /// </summary>
        public static string userAprovechamiento {
            get {
                return ResourceManager.GetString("userAprovechamiento", resourceCulture);
            }
        }
    }
}
