//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjeDeTrazado {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strEje {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strEje() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EjeDeTrazado.strEje", typeof(strEje).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A clotoide.
        /// </summary>
        public static string aclotoide {
            get {
                return ResourceManager.GetString("aclotoide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azimut final.
        /// </summary>
        public static string azimutfinal {
            get {
                return ResourceManager.GetString("azimutfinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curva radio 2500.
        /// </summary>
        public static string c2500 {
            get {
                return ResourceManager.GetString("c2500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curva radio 5000.
        /// </summary>
        public static string c5000 {
            get {
                return ResourceManager.GetString("c5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro curva X.
        /// </summary>
        public static string centrocurvax {
            get {
                return ResourceManager.GetString("centrocurvax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro curva Y .
        /// </summary>
        public static string centrocurvay {
            get {
                return ResourceManager.GetString("centrocurvay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curva de no paso.
        /// </summary>
        public static string CNP {
            get {
                return ResourceManager.GetString("CNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C.N.P. ángulo reducido.
        /// </summary>
        public static string CNPAnguloReducido {
            get {
                return ResourceManager.GetString("CNPAnguloReducido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curva de paso.
        /// </summary>
        public static string CP {
            get {
                return ResourceManager.GetString("CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curva.
        /// </summary>
        public static string curva {
            get {
                return ResourceManager.GetString("curva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento .
        /// </summary>
        public static string elemento {
            get {
                return ResourceManager.GetString("elemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clotoide.
        /// </summary>
        public static string espiral {
            get {
                return ResourceManager.GetString("espiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Giro de entrada.
        /// </summary>
        public static string GiroEntrada {
            get {
                return ResourceManager.GetString("GiroEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Giro de salida.
        /// </summary>
        public static string GiroSalida {
            get {
                return ResourceManager.GetString("GiroSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Línea.
        /// </summary>
        public static string linea {
            get {
                return ResourceManager.GetString("linea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud .
        /// </summary>
        public static string longitud {
            get {
                return ResourceManager.GetString("longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud de trazado.
        /// </summary>
        public static string longitudTrazado {
            get {
                return ResourceManager.GetString("longitudTrazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen derecha.
        /// </summary>
        public static string margender {
            get {
                return ResourceManager.GetString("margender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen izquierda.
        /// </summary>
        public static string margenizq {
            get {
                return ResourceManager.GetString("margenizq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No valorado.
        /// </summary>
        public static string NoValorado {
            get {
                return ResourceManager.GetString("NoValorado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peralte (%).
        /// </summary>
        public static string peralte {
            get {
                return ResourceManager.GetString("peralte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P.K. final.
        /// </summary>
        public static string pkfin {
            get {
                return ResourceManager.GetString("pkfin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P.K. inicial.
        /// </summary>
        public static string pkini {
            get {
                return ResourceManager.GetString("pkini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto fin X .
        /// </summary>
        public static string puntofinx {
            get {
                return ResourceManager.GetString("puntofinx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto fin Y .
        /// </summary>
        public static string puntofiny {
            get {
                return ResourceManager.GetString("puntofiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto inicio X .
        /// </summary>
        public static string puntoinix {
            get {
                return ResourceManager.GetString("puntoinix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto inicio Y .
        /// </summary>
        public static string puntoiniy {
            get {
                return ResourceManager.GetString("puntoiniy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Queda fijo.
        /// </summary>
        public static string QuedaFijo {
            get {
                return ResourceManager.GetString("QuedaFijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Radio .
        /// </summary>
        public static string radio {
            get {
                return ResourceManager.GetString("radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recta.
        /// </summary>
        public static string Recta {
            get {
                return ResourceManager.GetString("Recta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recta intermedia curva en S.
        /// </summary>
        public static string RectaIntermediaCurvaS {
            get {
                return ResourceManager.GetString("RectaIntermediaCurvaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recta intermedia paralelismo.
        /// </summary>
        public static string RectaIntermediaParalelismo {
            get {
                return ResourceManager.GetString("RectaIntermediaParalelismo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recta intermedia.
        /// </summary>
        public static string ResctaIntermedia {
            get {
                return ResourceManager.GetString("ResctaIntermedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segmento .
        /// </summary>
        public static string segmento {
            get {
                return ResourceManager.GetString("segmento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sentido giro.
        /// </summary>
        public static string sentgiro {
            get {
                return ResourceManager.GetString("sentgiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solución.
        /// </summary>
        public static string solucion {
            get {
                return ResourceManager.GetString("solucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo .
        /// </summary>
        public static string tipo {
            get {
                return ResourceManager.GetString("tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variación MI.
        /// </summary>
        public static string varimi {
            get {
                return ResourceManager.GetString("varimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variación MD .
        /// </summary>
        public static string varmd {
            get {
                return ResourceManager.GetString("varmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vértice.
        /// </summary>
        public static string vertice {
            get {
                return ResourceManager.GetString("vertice", resourceCulture);
            }
        }
    }
}
