//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tadLayLan {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strError() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tadLayLan.strError", typeof(strError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al insertar una línea en la capa {0}.
        /// </summary>
        public static string eAddLineaEnCapa {
            get {
                return ResourceManager.GetString("eAddLineaEnCapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error analizando el fichero :.
        /// </summary>
        public static string eAnalizandoFichero {
            get {
                return ResourceManager.GetString("eAnalizandoFichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la asiganción de notas máximas {0} y mínimas {1}.
        /// </summary>
        public static string eAsigancionValoresMaxMin {
            get {
                return ResourceManager.GetString("eAsigancionValoresMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible asignar la sección.
        /// </summary>
        public static string eAsignarSeccion {
            get {
                return ResourceManager.GetString("eAsignarSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERROR \n El bloque {0} no existe en el fichero actual.
        /// </summary>
        public static string eBloqueNoExisteFichero {
            get {
                return ResourceManager.GetString("eBloqueNoExisteFichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  La licencia ha caducado.
        /// </summary>
        public static string eCaducado {
            get {
                return ResourceManager.GetString("eCaducado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha elimado una capa que era necesaria.
        /// </summary>
        public static string eCapaEliminada {
            get {
                return ResourceManager.GetString("eCapaEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La capa {0} no está definida.
        /// </summary>
        public static string eCapaNoDefinida {
            get {
                return ResourceManager.GetString("eCapaNoDefinida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La capa {0} no existe en dwg actual.
        /// </summary>
        public static string eCapaNoExiste {
            get {
                return ResourceManager.GetString("eCapaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a \nCaso incompatible rotonda con pediente definida.
        /// </summary>
        public static string ecasoIncompatible {
            get {
                return ResourceManager.GetString("ecasoIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caso incompatible \nEs necesario definir tanto el azimut como la longitud de tramo.
        /// </summary>
        public static string eCasoIncomTramoSal {
            get {
                return ResourceManager.GetString("eCasoIncomTramoSal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caso indeterminado \n cotaCarretera {0}\n cotaTerreno {1}.
        /// </summary>
        public static string eCasoIndeterCotas {
            get {
                return ResourceManager.GetString("eCasoIndeterCotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caso indeterminado en el tramo de salida.
        /// </summary>
        public static string eCasoIndeterTramoSal {
            get {
                return ResourceManager.GetString("eCasoIndeterTramoSal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caso no contemplado.
        /// </summary>
        public static string eCasoNoContemplado {
            get {
                return ResourceManager.GetString("eCasoNoContemplado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de la estructura debe tener 6 caracteres \nCódigo estructura: {0}.
        /// </summary>
        public static string eCodigoSeccion {
            get {
                return ResourceManager.GetString("eCodigoSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El punto inicio y el punto fin no pueden coincidir.
        /// </summary>
        public static string eCoincidirPtoIniFin {
            get {
                return ResourceManager.GetString("eCoincidirPtoIniFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Colección de Tramos del Abanico es Nula.
        /// </summary>
        public static string eColeccionTramosNula {
            get {
                return ResourceManager.GetString("eColeccionTramosNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene elementos.
        /// </summary>
        public static string eComboCount0 {
            get {
                return ResourceManager.GetString("eComboCount0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El combo {0} no tiene definidos los IDs de búsqueda.
        /// </summary>
        public static string eComboFiltroNull {
            get {
                return ResourceManager.GetString("eComboFiltroNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el controlador de acceso a datos del interfaz gráfico.
        /// </summary>
        public static string eControladorAcceso {
            get {
                return ResourceManager.GetString("eControladorAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuneta trapezoidal.
        /// </summary>
        public static string eCunetaTrapezoidal {
            get {
                return ResourceManager.GetString("eCunetaTrapezoidal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El diccionario no contiene la clave {0}.
        /// </summary>
        public static string eDiccionarioNoContieneClave {
            get {
                return ResourceManager.GetString("eDiccionarioNoContieneClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al discretizar la polilínea; No existen puntos de intersección.
        /// </summary>
        public static string eDiscretizarPol {
            get {
                return ResourceManager.GetString("eDiscretizarPol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doble autovía.
        /// </summary>
        public static string eDobleAutovia {
            get {
                return ResourceManager.GetString("eDobleAutovia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doble autovía sin mediana.
        /// </summary>
        public static string eDobleAutoviaSinMediana {
            get {
                return ResourceManager.GetString("eDobleAutoviaSinMediana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El eje visibilidad está duplicado ; ({0} Ejes definidos en el proyecto,.
        /// </summary>
        public static string eEjeVisibiliadDuplicado {
            get {
                return ResourceManager.GetString("eEjeVisibiliadDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El eje visibilidad no se ha definido.
        /// </summary>
        public static string eEjeVisibilidadNoExiste {
            get {
                return ResourceManager.GetString("eEjeVisibilidadNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se está tratando de acceder a una entidad que no existe.
        /// </summary>
        public static string eEntidadNoExiste {
            get {
                return ResourceManager.GetString("eEntidadNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entidad {0}, solo puede tener dos vértices.
        /// </summary>
        public static string eEntidadSolo2Vertices {
            get {
                return ResourceManager.GetString("eEntidadSolo2Vertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La enumeración &apos;{0}&apos; no está implementada.
        /// </summary>
        public static string eEnumNoImplementada {
            get {
                return ResourceManager.GetString("eEnumNoImplementada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener el ID de licencia.
        /// </summary>
        public static string eErrorIDLic {
            get {
                return ResourceManager.GetString("eErrorIDLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en los campos del ID de licencia.
        /// </summary>
        public static string eErrorIDLicCampos {
            get {
                return ResourceManager.GetString("eErrorIDLicCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar el fichero.
        /// </summary>
        public static string eErrorSaveas {
            get {
                return ResourceManager.GetString("eErrorSaveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen estilos de etiqueta para ejes [Defina al menos uno].
        /// </summary>
        public static string eEstilosEtiquetaEje {
            get {
                return ResourceManager.GetString("eEstilosEtiquetaEje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Los estilos de visualización no estan configurados.
        /// </summary>
        public static string eEstiloVisualizacion {
            get {
                return ResourceManager.GetString("eEstiloVisualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay puntos fuera de la cartografía.
        /// </summary>
        public static string eExistenPuntosFueraCartografia {
            get {
                return ResourceManager.GetString("eExistenPuntosFueraCartografia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fichero Base Datos no existe.
        /// </summary>
        public static string eFicheroBBDDNoExiste {
            get {
                return ResourceManager.GetString("eFicheroBBDDNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fichero Normas [Vp-Kv] no existe.
        /// </summary>
        public static string eFicheroNormasNoExisteVpKv {
            get {
                return ResourceManager.GetString("eFicheroNormasNoExisteVpKv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fichero Normas [Vp-Rp] no existe.
        /// </summary>
        public static string eFicheroNormasNoExisteVpRp {
            get {
                return ResourceManager.GetString("eFicheroNormasNoExisteVpRp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear el filtro en la selección por capa-entidad.
        /// </summary>
        public static string eFiltroCapaEntidad {
            get {
                return ResourceManager.GetString("eFiltroCapaEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al generar el conjunto de selección.
        /// </summary>
        public static string eGenerarConjuntoSeleccion {
            get {
                return ResourceManager.GetString("eGenerarConjuntoSeleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener la región.
        /// </summary>
        public static string eGetRegion {
            get {
                return ResourceManager.GetString("eGetRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Conéctese a internet para ejecutar TADIL.
        /// </summary>
        public static string eInternet {
            get {
                return ResourceManager.GetString("eInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha configurado el valor inversión privada.
        /// </summary>
        public static string eInversionPrivada {
            get {
                return ResourceManager.GetString("eInversionPrivada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud {0} es inferior a AijMínimaSalida.
        /// </summary>
        public static string eLongitudMenorAjmin {
            get {
                return ResourceManager.GetString("eLongitudMenorAjmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud de salida es inferior a AijMínimaSalida.
        /// </summary>
        public static string eLongSalidaMenorA {
            get {
                return ResourceManager.GetString("eLongSalidaMenorA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Macro-Precios ; Seguridad y Salud.
        /// </summary>
        public static string eMacroPreciosSeguridadSauld {
            get {
                return ResourceManager.GetString("eMacroPreciosSeguridadSauld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código del material {0}, no esta implementado.
        /// </summary>
        public static string eMaterialCodeNotlmplemted {
            get {
                return ResourceManager.GetString("eMaterialCodeNotlmplemted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Método no implementado.
        /// </summary>
        public static string eMetodoNoImplementado {
            get {
                return ResourceManager.GetString("eMetodoNoImplementado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe.
        /// </summary>
        public static string eNoExiste {
            get {
                return ResourceManager.GetString("eNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe intersección entre los elementos.
        /// </summary>
        public static string eNoExistePuntosDeInterseccion {
            get {
                return ResourceManager.GetString("eNoExistePuntosDeInterseccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra el fichero de licencia.
        /// </summary>
        public static string eNoFichLic {
            get {
                return ResourceManager.GetString("eNoFichLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El fichero de licencia es nulo.
        /// </summary>
        public static string eNoFichLicNulo {
            get {
                return ResourceManager.GetString("eNoFichLicNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden obtener los datos extendidos de la clave {0}.
        /// </summary>
        public static string eNoSePuedeobtenerXdata {
            get {
                return ResourceManager.GetString("eNoSePuedeobtenerXdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La selección es Nula.
        /// </summary>
        public static string eNullSelection {
            get {
                return ResourceManager.GetString("eNullSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de intersecciones es mayor que uno.
        /// </summary>
        public static string eNumInterMayor1 {
            get {
                return ResourceManager.GetString("eNumInterMayor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La opción {0} no está configurada.
        /// </summary>
        public static string eOpcionNoConfig {
            get {
                return ResourceManager.GetString("eOpcionNoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener la polilínea entre dos puntos.
        /// </summary>
        public static string ePolilineaEntre2Puntos {
            get {
                return ResourceManager.GetString("ePolilineaEntre2Puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuesto.
        /// </summary>
        public static string ePresupuesto {
            get {
                return ResourceManager.GetString("ePresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso Cancelado.
        /// </summary>
        public static string eProcesoCancelado {
            get {
                return ResourceManager.GetString("eProcesoCancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad &apos;{0}&apos; no es solo de lectura.
        /// </summary>
        public static string ePropiedadLectura {
            get {
                return ResourceManager.GetString("ePropiedadLectura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad {0} es nula.
        /// </summary>
        public static string ePropiedadNula {
            get {
                return ResourceManager.GetString("ePropiedadNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad es nula.
        /// </summary>
        public static string ePropiedadNulaSinValor {
            get {
                return ResourceManager.GetString("ePropiedadNulaSinValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto ; MacroPrecios.
        /// </summary>
        public static string eProyectoMacroPrecios {
            get {
                return ResourceManager.GetString("eProyectoMacroPrecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se procesará el gálibo de la zona {0} ; Punto inicio o fin dentro.
        /// </summary>
        public static string ePuntoInicioFinDentroDeZonaCruce {
            get {
                return ResourceManager.GetString("ePuntoInicioFinDentroDeZonaCruce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El punto inicio o el punto fin no estan definidos.
        /// </summary>
        public static string ePuntoIniFinNoDef {
            get {
                return ResourceManager.GetString("ePuntoIniFinNoDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El punto no se encuentra en la polilínea.
        /// </summary>
        public static string ePuntoNoPolilinea {
            get {
                return ResourceManager.GetString("ePuntoNoPolilinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra el registro correspondiente al valor &apos;{0}&apos;\n en la tabla{1}.
        /// </summary>
        public static string eRegistroNoEncontrado {
            get {
                return ResourceManager.GetString("eRegistroNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro {0} de la tabla calzada única no existe.
        /// </summary>
        public static string eregistroTablaCalzadaUnicaNoExiste {
            get {
                return ResourceManager.GetString("eregistroTablaCalzadaUnicaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo puede existir un registro del valor &apos;{0}&apos;\n en la tabla{1}.
        /// </summary>
        public static string eRegistroUnico {
            get {
                return ResourceManager.GetString("eRegistroUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error sección calzada.
        /// </summary>
        public static string eSeccionCalzada {
            get {
                return ResourceManager.GetString("eSeccionCalzada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sección del Pk : {0} se encuentra fuera de la cartografia.
        /// </summary>
        public static string eSeccionFueraCarografia {
            get {
                return ResourceManager.GetString("eSeccionFueraCarografia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solución ; Eje Trazado (handle).
        /// </summary>
        public static string eSolucionEjeTrazado {
            get {
                return ResourceManager.GetString("eSolucionEjeTrazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solución con Id {0}\n no existe en el actual proyecto.
        /// </summary>
        public static string eSolucionNoExiste {
            get {
                return ResourceManager.GetString("eSolucionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla Cimentación.
        /// </summary>
        public static string eTablaCimentacion {
            get {
                return ResourceManager.GetString("eTablaCimentacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla Estudio informativo TDB.
        /// </summary>
        public static string eTablaEstInfTDB {
            get {
                return ResourceManager.GetString("eTablaEstInfTDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla Estructuras.
        /// </summary>
        public static string eTablaEstructuras {
            get {
                return ResourceManager.GetString("eTablaEstructuras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla Kv.
        /// </summary>
        public static string eTablaKV {
            get {
                return ResourceManager.GetString("eTablaKV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla Movimiento tierras.
        /// </summary>
        public static string eTablaMovTierras {
            get {
                return ResourceManager.GetString("eTablaMovTierras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla Proyecto.
        /// </summary>
        public static string eTablaProyecto {
            get {
                return ResourceManager.GetString("eTablaProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla punto inicio y fin.
        /// </summary>
        public static string eTablaPuntoIniFin {
            get {
                return ResourceManager.GetString("eTablaPuntoIniFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla Sección - Zonas Generales.
        /// </summary>
        public static string eTablaSeccionZGenerales {
            get {
                return ResourceManager.GetString("eTablaSeccionZGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla Solución.
        /// </summary>
        public static string eTablaSolucion {
            get {
                return ResourceManager.GetString("eTablaSolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla Túneles.
        /// </summary>
        public static string eTablaTuneles {
            get {
                return ResourceManager.GetString("eTablaTuneles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de calzada {0} no está implementada.
        /// </summary>
        public static string eTipoCalzadaNoImpl {
            get {
                return ResourceManager.GetString("eTipoCalzadaNoImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tramo de entronque no cumple los criterios de diseño.
        /// </summary>
        public static string eTramoEntronque {
            get {
                return ResourceManager.GetString("eTramoEntronque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para calcular un trazado con la tijera al menos hay que definir el azimut de entrada y el azimut de salida.
        /// </summary>
        public static string eTramoIniTramoFinNoConfigurado {
            get {
                return ResourceManager.GetString("eTramoIniTramoFinNoConfigurado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tramo de salida [Rotonda], es incompatible con los datos de diseño.
        /// </summary>
        public static string eTramoSalidaRotonda {
            get {
                return ResourceManager.GetString("eTramoSalidaRotonda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a existenTramosVálidosAvancesCortosLargos [Caso No Configurado].
        /// </summary>
        public static string eTramosValidos {
            get {
                return ResourceManager.GetString("eTramosValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen USB conectados al equipo.
        /// </summary>
        public static string eUSBNoConectado {
            get {
                return ResourceManager.GetString("eUSBNoConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la validación de datos del formulario.
        /// </summary>
        public static string eValidacion {
            get {
                return ResourceManager.GetString("eValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Fuera de Rango ; Valor Máximo {0}.
        /// </summary>
        public static string eValorMaxOutRango {
            get {
                return ResourceManager.GetString("eValorMaxOutRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Fuera de Rango ; Valor Mínimo  {0}.
        /// </summary>
        public static string eValorMinOutRango {
            get {
                return ResourceManager.GetString("eValorMinOutRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor {0}\n no se ha configurado.
        /// </summary>
        public static string eValorNoconfig {
            get {
                return ResourceManager.GetString("eValorNoconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor {0} no está implementado.
        /// </summary>
        public static string eValorNoImplementado {
            get {
                return ResourceManager.GetString("eValorNoImplementado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor obligatorio.
        /// </summary>
        public static string eValorObligatorio {
            get {
                return ResourceManager.GetString("eValorObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud del texto está fuera de rango ; Valor máximo {0}.
        /// </summary>
        public static string eValorStrMaxOutRango {
            get {
                return ResourceManager.GetString("eValorStrMaxOutRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la valoración de la sección: \nValor Máximo: {0} \nValorMínimo: {1} \nValor Sección: {3}.
        /// </summary>
        public static string eValSeccion {
            get {
                return ResourceManager.GetString("eValSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las zonas generales no pueden ser zonas de no paso.
        /// </summary>
        public static string eZonaGeneralNP {
            get {
                return ResourceManager.GetString("eZonaGeneralNP", resourceCulture);
            }
        }
    }
}
