//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tadLayLan {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strGeneralUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strGeneralUser() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tadLayLan.strGeneralUser", typeof(strGeneralUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analizando el abanico {0} ; Tramo {1} ; Posición {2}.
        /// </summary>
        public static string uiAnalizandoAbanico {
            get {
                return ResourceManager.GetString("uiAnalizandoAbanico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Deseas borrar el registro? .
        /// </summary>
        public static string uiBorrarRegistro {
            get {
                return ResourceManager.GetString("uiBorrarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Deseas Borrar el Conjunto de Registros?.
        /// </summary>
        public static string uiBorrarRegistroListados {
            get {
                return ResourceManager.GetString("uiBorrarRegistroListados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Deseas Borrar el Registro?.
        /// </summary>
        public static string uiBorrarRegistroUnico {
            get {
                return ResourceManager.GetString("uiBorrarRegistroUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Deseas Cancelar las Modificaciones?.
        /// </summary>
        public static string uiCancelarModificaciones {
            get {
                return ResourceManager.GetString("uiCancelarModificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se deben completar las pestañas anteriores.
        /// </summary>
        public static string uiCompletarLasPestAnteriores {
            get {
                return ResourceManager.GetString("uiCompletarLasPestAnteriores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dato No Valido.
        /// </summary>
        public static string uiDatoNoValido {
            get {
                return ResourceManager.GetString("uiDatoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Deseas Guardar los Datos?.
        /// </summary>
        public static string uiDatosGuardar {
            get {
                return ResourceManager.GetString("uiDatosGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existen Datos No Guardados.
        /// </summary>
        public static string uiDatosNoGuardados {
            get {
                return ResourceManager.GetString("uiDatosNoGuardados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la Validación de los Datos.
        /// </summary>
        public static string uiDatosNoValidos {
            get {
                return ResourceManager.GetString("uiDatosNoValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Restaurados.
        /// </summary>
        public static string uiDatosRestaurados {
            get {
                return ResourceManager.GetString("uiDatosRestaurados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Guardados.
        /// </summary>
        public static string uiDatosSaveIsOk {
            get {
                return ResourceManager.GetString("uiDatosSaveIsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Conjunto de Filas esta vacio.
        /// </summary>
        public static string uiDgvRowEmpty {
            get {
                return ResourceManager.GetString("uiDgvRowEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo Debes de Selecionar un Registro.
        /// </summary>
        public static string uiDgvRowMultiple {
            get {
                return ResourceManager.GetString("uiDgvRowMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes de Seleccionar un Registro.
        /// </summary>
        public static string uiDgvRowNull {
            get {
                return ResourceManager.GetString("uiDgvRowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primero debes crear el perfil longitudinal.
        /// </summary>
        public static string uiEjePerfilNoExiste {
            get {
                return ResourceManager.GetString("uiEjePerfilNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Eje de Trazado ya existe.
        /// </summary>
        public static string uiEjeTrazadoCreado {
            get {
                return ResourceManager.GetString("uiEjeTrazadoCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primero debes generar el eje de trazado.
        /// </summary>
        public static string uiEjeTrazadoNoExiste {
            get {
                return ResourceManager.GetString("uiEjeTrazadoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Entidad con Identificados {0} \No se encuentra en el actual fichero.
        /// </summary>
        public static string uiEntidadNotFound {
            get {
                return ResourceManager.GetString("uiEntidadNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es recomendable borrar el registro asociada a la entidad.
        /// </summary>
        public static string uiEntidadNotFoundRecomendacion {
            get {
                return ResourceManager.GetString("uiEntidadNotFoundRecomendacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID de la entidad polilínea es {0}.
        /// </summary>
        public static string uiEntidadPolilinea {
            get {
                return ResourceManager.GetString("uiEntidadPolilinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen entidades que exportar.
        /// </summary>
        public static string uiExportarEntidadesNotFound {
            get {
                return ResourceManager.GetString("uiExportarEntidadesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primero se debe completar la tabla &quot;Sección tipo y zonas generales&quot;.
        /// </summary>
        public static string uiFaltanDatosEjeBasico {
            get {
                return ResourceManager.GetString("uiFaltanDatosEjeBasico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fichero generado con éxito.
        /// </summary>
        public static string uiFicheroExito {
            get {
                return ResourceManager.GetString("uiFicheroExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un Archivo de Proyecto.
        /// </summary>
        public static string uiFileAppSelect {
            get {
                return ResourceManager.GetString("uiFileAppSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una Base Datos Tadil .
        /// </summary>
        public static string uiFileBbSelect {
            get {
                return ResourceManager.GetString("uiFileBbSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo de Datos Cargado.
        /// </summary>
        public static string uiFileDataLoadOk {
            get {
                return ResourceManager.GetString("uiFileDataLoadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El fichero {0} 
        ///No Se Encuentra.
        /// </summary>
        public static string uiFileNotFound {
            get {
                return ResourceManager.GetString("uiFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El fichero {0} no se encuentra en la carpeta img.
        /// </summary>
        public static string uiFileNotFoundImg {
            get {
                return ResourceManager.GetString("uiFileNotFoundImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El fichero {0} 
        ///No Se Encuentra
        ///Selecciona Nueva Ruta.
        /// </summary>
        public static string uiFileNotFoundSelectOrigen {
            get {
                return ResourceManager.GetString("uiFileNotFoundSelectOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe guardar los datos del terreno antes de crear la envolvente.
        /// </summary>
        public static string uiGuardaTerreno {
            get {
                return ResourceManager.GetString("uiGuardaTerreno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a InformeMediciones.
        /// </summary>
        public static string uiInformeMediciones {
            get {
                return ResourceManager.GetString("uiInformeMediciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a InformeObraLineal.
        /// </summary>
        public static string uiInformesObraLineal {
            get {
                return ResourceManager.GetString("uiInformesObraLineal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado secciones con errores.
        /// </summary>
        public static string uiListadoSeccionesError {
            get {
                return ResourceManager.GetString("uiListadoSeccionesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha cargado ninguna Base de Datos.
        /// </summary>
        public static string uiNoBBDD {
            get {
                return ResourceManager.GetString("uiNoBBDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has deleccionado ningún fichero.
        /// </summary>
        public static string uiNoFichSelecionado {
            get {
                return ResourceManager.GetString("uiNoFichSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los nombres no pueden contener carácteres especiales.
        /// </summary>
        public static string uiNombreConCaracteresEspeciales {
            get {
                return ResourceManager.GetString("uiNombreConCaracteresEspeciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del fichero es nulo.
        /// </summary>
        public static string uiNomFichNulo {
            get {
                return ResourceManager.GetString("uiNomFichNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha seleccionado ningún terreno.
        /// </summary>
        public static string uiNoTerrenoSeleccionado {
            get {
                return ResourceManager.GetString("uiNoTerrenoSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Obra Lineal ya existe.
        /// </summary>
        public static string uiObraLinealCreado {
            get {
                return ResourceManager.GetString("uiObraLinealCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Obra Lineal ya fue exportada.
        /// </summary>
        public static string uiObraLinealExportarRealizado {
            get {
                return ResourceManager.GetString("uiObraLinealExportarRealizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Perfil Longitudinal ya existe.
        /// </summary>
        public static string uiPerfilCreado {
            get {
                return ResourceManager.GetString("uiPerfilCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primero debes de generar el perfil longitudinal civil3D.
        /// </summary>
        public static string uiPerfilLongitudinalCivilNoExiste {
            get {
                return ResourceManager.GetString("uiPerfilLongitudinalCivilNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede vincular una polilinea abierta a una zona GIS.
        /// </summary>
        public static string uiPolilineaAbiertaErronea {
            get {
                return ResourceManager.GetString("uiPolilineaAbiertaErronea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden introducir polilíneas 3D para crear el MDT.
        /// </summary>
        public static string uiPolilinieas3dNoValidas {
            get {
                return ResourceManager.GetString("uiPolilinieas3dNoValidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso Anulado.
        /// </summary>
        public static string uiProcesoAnulado {
            get {
                return ResourceManager.GetString("uiProcesoAnulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La distancia entre el punto inicio y el punto fin es menor o 2*A.
        /// </summary>
        public static string uiPtoIniPtoFinMuyCercanos {
            get {
                return ResourceManager.GetString("uiPtoIniPtoFinMuyCercanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Cerrado Sin Guardar Datos.
        /// </summary>
        public static string uiSalirDatosSinGuardar {
            get {
                return ResourceManager.GetString("uiSalirDatosSinGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos No Modificados.
        /// </summary>
        public static string uiSalirDatosSinModificar {
            get {
                return ResourceManager.GetString("uiSalirDatosSinModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Deseas Cerrar el Formulario?.
        /// </summary>
        public static string uiSalirPregunta {
            get {
                return ResourceManager.GetString("uiSalirPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes seleccionar al menos 2 soluciones\n para iniciar el proceso de valoración.
        /// </summary>
        public static string uiSel2Soluciones {
            get {
                return ResourceManager.GetString("uiSel2Soluciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a \n Selecciona los puntos de la polilínea.
        /// </summary>
        public static string uiSeleccionaPuntosDePolilinea {
            get {
                return ResourceManager.GetString("uiSeleccionaPuntosDePolilinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes seleccionar una solución.
        /// </summary>
        public static string uiSelecSolucion {
            get {
                return ResourceManager.GetString("uiSelecSolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un Eje de Visibilildad.
        /// </summary>
        public static string uiSelectEjeBasico {
            get {
                return ResourceManager.GetString("uiSelectEjeBasico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La selección es nula.
        /// </summary>
        public static string uiSelectIsNull {
            get {
                return ResourceManager.GetString("uiSelectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes seleccionar una hipótesis de valoración.
        /// </summary>
        public static string uiSelHipotesis {
            get {
                return ResourceManager.GetString("uiSelHipotesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione polilinea envolvente.
        /// </summary>
        public static string uiSelPolEnvolvente {
            get {
                return ResourceManager.GetString("uiSelPolEnvolvente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecione el conjunto de polilíneas que quiere simplificar.
        /// </summary>
        public static string uiSelPolilineas {
            get {
                return ResourceManager.GetString("uiSelPolilineas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe solución envolvente máxima .
        /// </summary>
        public static string uiSolucionEnvolventeMaximaNotFound {
            get {
                return ResourceManager.GetString("uiSolucionEnvolventeMaximaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe solución envolvente mínima.
        /// </summary>
        public static string uiSolucionenvolventeMinimaNotFound {
            get {
                return ResourceManager.GetString("uiSolucionenvolventeMinimaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe solución con los parámetros de diseño inicial.
        /// </summary>
        public static string uiSolucionPrimariaNotFound {
            get {
                return ResourceManager.GetString("uiSolucionPrimariaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La suma de porcentajes no es 100 :\n {0}.
        /// </summary>
        public static string uiSumaPorcentajes {
            get {
                return ResourceManager.GetString("uiSumaPorcentajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha configurado el TAG del campo {0}.
        /// </summary>
        public static string uiTAGNoConfig {
            get {
                return ResourceManager.GetString("uiTAGNoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes abrir el formulario TDB
        ///Antes debes de cerrar el formulario TDI.
        /// </summary>
        public static string uiTDBnoPerimiteInstancia {
            get {
                return ResourceManager.GetString("uiTDBnoPerimiteInstancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes abrir el formulario TDI
        ///Antes debes de cerrar el formulario TDB.
        /// </summary>
        public static string uiTDInoPermiteInstancia {
            get {
                return ResourceManager.GetString("uiTDInoPermiteInstancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Tramo de Llegada no cumple con las especificaciones del diseño.
        /// </summary>
        public static string uiTramoLlegadaNoCumple {
            get {
                return ResourceManager.GetString("uiTramoLlegadaNoCumple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Tramo de Salida no cumple con las especificaciones del diseño.
        /// </summary>
        public static string uiTramoSalidaNoCumple {
            get {
                return ResourceManager.GetString("uiTramoSalidaNoCumple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se pretende pasar por una zona etiquetada como de no paso.
        /// </summary>
        public static string uiZonaNoPaso {
            get {
                return ResourceManager.GetString("uiZonaNoPaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La zona {0} esta etiquetada como de no paso.
        /// </summary>
        public static string uiZonaNoPasoConNombre {
            get {
                return ResourceManager.GetString("uiZonaNoPasoConNombre", resourceCulture);
            }
        }
    }
}
