//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tadLayLan {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strGeneralUser1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strGeneralUser1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tadLayLan.strGeneralUser1", typeof(strGeneralUser1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicación cargada con éxito.
        /// </summary>
        public static string uiAplicacionCargadaExito {
            get {
                return ResourceManager.GetString("uiAplicacionCargadaExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de comandos.
        /// </summary>
        public static string uiComListado {
            get {
                return ResourceManager.GetString("uiComListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar gestor base datos.
        /// </summary>
        public static string uiComTdb {
            get {
                return ResourceManager.GetString("uiComTdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tden -&gt; Idioma Inglés.
        /// </summary>
        public static string uiComTdEn {
            get {
                return ResourceManager.GetString("uiComTdEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tdes -&gt; Idioma Español.
        /// </summary>
        public static string uiComTdEs {
            get {
                return ResourceManager.GetString("uiComTdEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tdfr -&gt; Idioma Francés.
        /// </summary>
        public static string uiComTdFr {
            get {
                return ResourceManager.GetString("uiComTdFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar gestor de proyectos.
        /// </summary>
        public static string uiComTdi {
            get {
                return ResourceManager.GetString("uiComTdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tdrem -&gt; Descargar aplicación.
        /// </summary>
        public static string uiComTdRem {
            get {
                return ResourceManager.GetString("uiComTdRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tdset -&gt; Configurar aplicación (Inicio automático próximas sesiones).
        /// </summary>
        public static string uiComTdset {
            get {
                return ResourceManager.GetString("uiComTdset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma Inglés.
        /// </summary>
        public static string uiConfigEN {
            get {
                return ResourceManager.GetString("uiConfigEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma Francés.
        /// </summary>
        public static string uiConfigFR {
            get {
                return ResourceManager.GetString("uiConfigFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma Español.
        /// </summary>
        public static string uiCongigES {
            get {
                return ResourceManager.GetString("uiCongigES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la validación de datos.
        /// </summary>
        public static string uiErrorValidarDatos {
            get {
                return ResourceManager.GetString("uiErrorValidarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string uiGuardaTerreno {
            get {
                return ResourceManager.GetString("uiGuardaTerreno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso cancelado.
        /// </summary>
        public static string uiProcesoCancelado {
            get {
                return ResourceManager.GetString("uiProcesoCancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso terminado.
        /// </summary>
        public static string uiProcesoTerminado {
            get {
                return ResourceManager.GetString("uiProcesoTerminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso terminado
        ///Tiempo de proceso {0} [min].
        /// </summary>
        public static string uiProcesoTerminadoConTiempoMinutos {
            get {
                return ResourceManager.GetString("uiProcesoTerminadoConTiempoMinutos", resourceCulture);
            }
        }
    }
}
