//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tadLayLan {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strUserCad {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strUserCad() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tadLayLan.strUserCad", typeof(strUserCad).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generando la entidad {0} del eje de trazado.
        /// </summary>
        public static string uiGenerandoEntidadesEjeTrazado {
            get {
                return ResourceManager.GetString("uiGenerandoEntidadesEjeTrazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generando la sección {0}.
        /// </summary>
        public static string uiGenerandolaSeccion {
            get {
                return ResourceManager.GetString("uiGenerandolaSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El punto seleccionado esta dentro de la franja no util en borde de cartografía.
        /// </summary>
        public static string uiPointCercaBorde {
            get {
                return ResourceManager.GetString("uiPointCercaBorde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El punto se encuentra fuera de la cartografía.
        /// </summary>
        public static string uiPointOutCartografia {
            get {
                return ResourceManager.GetString("uiPointOutCartografia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un punto.
        /// </summary>
        public static string uiPointSelect {
            get {
                return ResourceManager.GetString("uiPointSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El punto se encuentra dentro de una zona de no paso.
        /// </summary>
        public static string uiPointZNP {
            get {
                return ResourceManager.GetString("uiPointZNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una polilinea.
        /// </summary>
        public static string uiPolilineaSelect {
            get {
                return ResourceManager.GetString("uiPolilineaSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entidad seleccionada no es una polilinea.
        /// </summary>
        public static string uiPolilineaSelectFail {
            get {
                return ResourceManager.GetString("uiPolilineaSelectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un punto para insertar el perfil longitudinal.
        /// </summary>
        public static string uiSelectPtoInsertPerfilLongitudinal {
            get {
                return ResourceManager.GetString("uiSelectPtoInsertPerfilLongitudinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un punto para insertar las secciones transversales.
        /// </summary>
        public static string uiSelectPtoInsertSecciones {
            get {
                return ResourceManager.GetString("uiSelectPtoInsertSecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un punto que este dentro del triangulo que quieres eliminar.
        /// </summary>
        public static string uiSelectPtoInsideTriangle {
            get {
                return ResourceManager.GetString("uiSelectPtoInsideTriangle", resourceCulture);
            }
        }
    }
}
